### PR TITLE
Add gif-provider so we can support multiple APIs [#11]

### PR DESCRIPTION
**Pull request by jamescallumyoung**
For #11.

Replaces the giphy-api dependency with gif-provider, and updates gifBox and gifItem accordingly.
This allows us to consume any extra APIs gif-provider supports in the future with only trivial changes and allows us to support the Tenor API right now 🎉 .

### CODE REVIEW

**Comment by jamescallumyoung** [comment]
@joshghent, if this builds and tests okay, it's safe to merge. I can't test it locally very well though so I'd appreciate if you could take a look?

~I'll update gif-provider to support Tenor later today so support for Tenor will probably come to gifbox late tomorrow.~

I updated gif-provider so now it supports both Giphy and Tenor. We're now automatically querying both of them.

**Comment by jamescallumyoung** [comment]
Hey, @joshghent, can you merge?

**Comment by joshghent** [comment]
Hey @jamescallumyoung - apologies for not looking at this sooner (got a new house so a bit mental)!
This is absolutely awesome! I can't believe you've got through this much trouble to add to this project! It's amazing mate. Great code and implementation. Cool idea to spin that out into it's own new repo too. Nice work. I've added you as a contributor to this project so you can commit directly to it 👍

**Comment by jamescallumyoung** [comment]
@joshghent. Congrats on the new house! I also moved recently so I know it can be a bit chaotic 😆.

> This is absolutely awesome! I can't believe you've got through this much trouble to add to this project! It's amazing mate. Great code and implementation. Cool idea to spin that out into it's own new repo too. Nice work.

Thanks! I really enjoyed this PR too so I'm sure it won't be too long until you see some more from me 👍 

>  I've added you as a contributor to this project so you can commit directly to it 👍

Awesome! Thanks again!

**Comment by joshghent** [comment]
@jamescallumyoung Haha congratulations likewise! Yeah it's a bit crazy but nothing a few B&Q trips and an impact driver won't sort 😂 

Look forward to seeing more contributions from you 👍

**Pull request merged**
