### PR TITLE
created eslint file

### PR DESCRIPTION
**Pull request by dhuang612**
initialized new eslint file and set the rules to airbnb
ran tests and confirmed there were no errors.

### CODE REVIEW

**Comment by joshghent** [comment]
@dhuang612 Nice work dude, this is awesome! Any chance we can please add this as a step in the travis config please?

**Comment by dhuang612** [comment]
@joshghent sure thing.
Completed and squashed extra commit.
**updated**
simplified the travis.yml configuration file. 
Let me know if there is anything else that needs to be done!

**Comment by dhuang612** [comment]
noticed that this application runs with yarn, switched the travis config to yarn lint

**Comment by joshghent** [comment]
Awesome stuff @dhuang612! Thank you so much! 🎉 
Hope you enjoyed contributing to open source! There are many more issues on this repo and others that you'd be more than welcome to take your pick of!

**Pull request merged**
