### PR TITLE
Setup automated tests with Jest

### PR DESCRIPTION
**Pull request by Fabianopb**
Here is your test suite up and running! I haven't written tests for everything, though, I recommend another PR for refactoring components to be more testable and writing tests for what's missing.

* Jest is configured to run with a coverage report at the end through `test` script
* `test:watch [fileName]` allows you to watch in real time test development
* `enzyme` has been installed to give you a nice API for testing React components
* Travis-CI is configured (very basic config, make sure your Travis-CI account enables access to your repos)

### CODE REVIEW

**Comment by Fabianopb** [comment]
Oh, almost forgot, I noticed you have both `package-lock` and `yarn.lock`, I'd suggest choosing either `npm` *or* `yarn` (personally I prefer yarn atm) and removing the lock file related to the other package manager. Also, if you choose yarn remember to update your scripts that currently use npm to use yarn instead.

**Comment by joshghent** [comment]
@Fabianopb This is absolutely awesome! I've not done any testing with React so this is really eye opening for me. Thanks a bunch for setting this up! I hope to add more tests to this and improve functionality along with it 👍 

Good shout on the yarn or npm thing. We will go with Yarn since that has all the commands setup and has been super quick for me on this project. Perhaps we can create a new issue for that?

**Comment by Fabianopb** [comment]
No problem, I'm glad to help! Let me know if you have any doubts about the setup!
And yeah, you could create a new issue for that, it's not deadly serious, but it's a good way to keep track!

**Comment by joshghent** [comment]
@Fabianopb I've created #16 to handle this! Completely agree dude, just cleans it up a bit :+1:

**Pull request merged**
