### PR TITLE
Fix not building issues

### PR DESCRIPTION
**Pull request by joshghent**

### CODE REVIEW

**Comment by joshghent** [comment]
Screenshot 2020-01-21 at 08 31 37
Current error when attempting to start the app

**Comment by tsonge** [comment]
Hi @joshghent  Thanks for responding to my PR earlier.

I think that error can be fixed by using `import { menubar } from 'menubar'` or `const menubar = require('menubar').menubar`, if you prefer CommonJS syntax.

After that though, we'd get a index.html file not found error that looks like: 
```
yarn run v1.21.1
$ electron .
menubar:  Error: ERR_FILE_NOT_FOUND (-6) loading 'file:///Users/tsonge/gifbar-1/gifbar/dist/app/index.html'
    at rejectAndCleanup (electron/js2c/browser_init.js:5883:21)
    at WebContents.failListener (electron/js2c/browser_init.js:5893:11)
    at WebContents.emit (events.js:203:13) {
  errno: -6,
  code: 'ERR_FILE_NOT_FOUND',
  url: 'file:///Users/tsonge/gifbar-1/gifbar/dist/app/index.html'
}
```

and I think this is because electron (or menubar) is searching for the index.html file to display (when you open the menubar). 

I solved this in my earlier PR by basically just adding my own index.html file.

**Comment by joshghent** [comment]
You're absolutely right @tsonge - that was the problem. Although I've found that the styles have gone so I'm going to keep this PR open so I can rewrite them (according to the style in the gif on the readme). Feel free to chip in if you are able 👍 Thank you for your help with this

**Comment by jamescallumyoung** [comment]
Closed as stale

**Pull request closed without merging**
