### PR TITLE
removed packages that weren't being used

### PR DESCRIPTION
**Pull request by dhuang612**
So the build is failing according to github.

I opened an issue related to this and investigated
According to this:
https://github.com/microsoft/node-pty/issues/319

It's something to do with node v 12 and windows builds.
They recommended installing node-pty@beta as a dev dependency which I did.
I'll review the travis logs to see if this resolves that.

The bundlesize command under package.json wasn't working.

updated bundlesize.config.json to accept module blobs
```
path": "dist/**/*.js",
```

tested and confirmed it can now review the bundle sizes of the dist folder.

removed lodash package from package.json
and added the two individual modules that are being used in this project
.isEmpty & .map

removed giphy package as it wasn't being used
giphy-api is being used, left as is.

removed electron-debug package as it wasn't being used.

switched .travis.yml back to use npm run lint since yarn doesn't seem to be configured with this project.
tested this by cloning a fresh project down to computer when you run yarn start
```
yarn: command not found
```

Let me know if there is anything else that needs to be changed!

### CODE REVIEW

**Comment by joshghent** [comment]
Looks good to me! Thanks a lot for your work! @dhuang612! 👍

**Review by jamescallumyoung — APPROVED** [review]
Looks fine to me. 👍 

The gif-provider module provides it's own giphy-api dependency so we can remove that here.

**Comment by jamescallumyoung** [comment]
Hey @joshghent, this looks  fine by me. I won't merge it until you approve it too though. Feel free to merge yourself if you approve 👍 

@dhuang612 Thanks for the help here 👍 Good stuff.

**Comment by joshghent** [comment]
@jamescallumyoung thanks for reviewing that mate 👍 Great work @dhuang612 🎉

**Pull request merged**
